import { TField } from '@/types'

export const OPERATORS = {
  bool: { equals: 'Equals', notEquals: 'Not Equals' },
  text: {
    equals: 'Equals',
    notEquals: 'Not Equals',
    likes: 'Likes',
    notLikes: 'Not Likes',
    containAll: 'Contains All',
  },
  number: {
    equals: 'Equals',
    gt: 'Greater than',
    gte: 'Greater than Equal',
    lt: 'Less than',
    lte: 'Less than Equal',
    between: 'Between',
  },
  time: {
    between: 'Between',
    gte: 'Greater than Equal',
    lte: 'Less than Equal',
    equals: 'Equals',
  },
} as const

export const MOCK_DATA: TField[] = [
  {
    key: 'customField13',
    sysIndexKey: 'customField13',
    name: 'Transaction Time (Text)',
    dataType: 'String',
    refType: null,
    ctxMasterDataRef: null,
  },
  {
    key: 'customFieldDouble01',
    sysIndexKey: 'customFieldDouble01',
    name: 'Value',
    dataType: 'Double',
    refType: null,
    ctxMasterDataRef: null,
  },
  {
    key: 'customFieldLong01',
    sysIndexKey: 'customFieldLong01',
    name: 'Quantity',
    dataType: 'Long',
    refType: null,
    ctxMasterDataRef: null,
  },
  {
    key: 'customFieldTimestamp01',
    sysIndexKey: 'customFieldTimestamp01',
    name: 'Transaction Time',
    dataType: 'Timestamp',
    refType: null,
    ctxMasterDataRef: null,
  },
  // {
  //   key: 'record_id',
  //   sysIndexKey: 'id',
  //   name: 'Record Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'system_name',
  //   sysIndexKey: 'systemName',
  //   name: 'System name',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'ref_id',
  //   sysIndexKey: 'refId',
  //   name: 'Ref Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customer_id',
  //   sysIndexKey: 'customerId',
  //   name: 'Customer Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'phone',
  //   sysIndexKey: 'phone',
  //   name: 'Phone Number',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'email',
  //   sysIndexKey: 'email',
  //   name: 'Email Address',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'user_id',
  //   sysIndexKey: 'userId',
  //   name: 'User Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'lead_id',
  //   sysIndexKey: 'leadId',
  //   name: 'Lead Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'device_id',
  //   sysIndexKey: 'deviceId',
  //   name: 'Device Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'eventCtg',
  //   sysIndexKey: 'eventCtg',
  //   name: 'Event Category',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'event',
  //   sysIndexKey: 'event',
  //   name: 'Event Name',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'eventLabel',
  //   sysIndexKey: 'eventLabel',
  //   name: 'Event Label',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'ggCid',
  //   sysIndexKey: 'ggCid',
  //   name: 'Google Cid',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'ggTid',
  //   sysIndexKey: 'ggTid',
  //   name: 'Google Tid',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'fbPid',
  //   sysIndexKey: 'fbPid',
  //   name: 'FB Pixel Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'fbCId',
  //   sysIndexKey: 'fbCId',
  //   name: 'FB Psid',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'zoOAId',
  //   sysIndexKey: 'zoOAId',
  //   name: 'ZOA Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'zoUId',
  //   sysIndexKey: 'zoUId',
  //   name: 'ZOA Uid',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'fcmToken',
  //   sysIndexKey: 'fcmToken',
  //   name: 'FCM Token',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'prevVersion',
  //   sysIndexKey: 'prevVersion',
  //   name: 'Previous Version',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'modelCreatedAt',
  //   sysIndexKey: 'modelCreatedAt',
  //   name: 'Created Time',
  //   dataType: 'Timestamp',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'modelUpdatedAt',
  //   sysIndexKey: 'modelUpdatedAt',
  //   name: 'Updated Time',
  //   dataType: 'Timestamp',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'createdAt',
  //   sysIndexKey: 'createdAt',
  //   name: 'System Created Time',
  //   dataType: 'Timestamp',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'updatedAt',
  //   sysIndexKey: 'updatedAt',
  //   name: 'System Updated Time',
  //   dataType: 'Timestamp',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'data_source',
  //   sysIndexKey: 'datasource',
  //   name: 'Data Source',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'tags',
  //   sysIndexKey: 'tags',
  //   name: 'Tags',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'recordStatus',
  //   sysIndexKey: 'recordStatus',
  //   name: 'Record Status',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField01',
  //   sysIndexKey: 'customField01',
  //   name: 'Product Name',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField02',
  //   sysIndexKey: 'customField02',
  //   name: 'Product Id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField03',
  //   sysIndexKey: 'customField03',
  //   name: 'Product SKU',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField04',
  //   sysIndexKey: 'customField04',
  //   name: 'Product Category',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField05',
  //   sysIndexKey: 'customField05',
  //   name: 'Product Brand Code',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField06',
  //   sysIndexKey: 'customField06',
  //   name: 'Type_id',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField07',
  //   sysIndexKey: 'customField07',
  //   name: 'Type_name',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField08',
  //   sysIndexKey: 'customField08',
  //   name: 'Customer Name',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField09',
  //   sysIndexKey: 'customField09',
  //   name: 'Address Line',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField10',
  //   sysIndexKey: 'customField10',
  //   name: 'Ward',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField11',
  //   sysIndexKey: 'customField11',
  //   name: 'District',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField12',
  //   sysIndexKey: 'customField12',
  //   name: 'City',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customField13',
  //   sysIndexKey: 'customField13',
  //   name: 'Transaction Time (Text)',
  //   dataType: 'String',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customFieldDouble01',
  //   sysIndexKey: 'customFieldDouble01',
  //   name: 'Value',
  //   dataType: 'Double',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customFieldLong01',
  //   sysIndexKey: 'customFieldLong01',
  //   name: 'Quantity',
  //   dataType: 'Long',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
  // {
  //   key: 'customFieldTimestamp01',
  //   sysIndexKey: 'customFieldTimestamp01',
  //   name: 'Transaction Time',
  //   dataType: 'Timestamp',
  //   refType: null,
  //   ctxMasterDataRef: null,
  // },
]
